<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text18_text18</name>
   <tag></tag>
   <elementGuidId>bbdf0a4b-2ca6-4731-9bb9-daf344b21f64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text18']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#text18</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d8c7cc6a-ca7c-4d94-bdec-fecc3c132392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>26cfbc1b-863f-44bc-9c67-024eebb62271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text18</value>
      <webElementGuid>23a7e326-207a-44f7-8e77-8678e524894b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text18&quot;)</value>
      <webElementGuid>beca6f72-ff2d-42bd-8969-41a029340683</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text18']</value>
      <webElementGuid>3ef7af57-6fbc-4991-8d5c-74325316accc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[18]</value>
      <webElementGuid>a7d42d6a-a21a-4d58-bb2e-b769d3f66865</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text18']</value>
      <webElementGuid>8da3290c-cd2c-436d-b5f1-9a02c2bb9253</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
