<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text39_text39</name>
   <tag></tag>
   <elementGuidId>a049e326-6ae5-4c31-b04d-4c0534118cb9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text39']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#text39</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eec9dc44-03dc-4a38-b060-5c5d8c7ef0e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1aed48d7-c350-4678-bf7c-3e4524fcd7de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text39</value>
      <webElementGuid>906a63d0-55d6-4197-8b3b-5428f6a8451a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text39&quot;)</value>
      <webElementGuid>dd87683e-60bc-4bf6-9769-90d45dce7799</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text39']</value>
      <webElementGuid>99df027f-314f-42fb-8294-950d994ff83a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[39]</value>
      <webElementGuid>a55d107f-74ae-4cfe-b5c5-f21a0cdb1c19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text39']</value>
      <webElementGuid>7ec8309c-dee7-44b4-ab87-06d3389150f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
