<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text15_text15</name>
   <tag></tag>
   <elementGuidId>d8ddb932-bac5-4490-a072-afd3f6318bb5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text15']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#text15</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b17e2e4d-b8b3-47c5-ba72-1264c115b9ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>800a94f3-d8e6-48a2-8a3e-de6f9cd90f12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text15</value>
      <webElementGuid>c7831791-6323-486a-ae32-189127f17fba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text15&quot;)</value>
      <webElementGuid>49e18d3c-2cca-4ae3-9195-bfef9dac45fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text15']</value>
      <webElementGuid>2c5ad5d8-fb52-4e8c-97fe-50140bb3013b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[15]</value>
      <webElementGuid>2f450557-8631-4e2c-99b1-b69e685ba4e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text15']</value>
      <webElementGuid>0445e32a-3495-4341-88bb-d28cbaf4090b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
