<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Text8_text8</name>
   <tag></tag>
   <elementGuidId>89d4846b-9d88-4574-946c-7c3a4d4454fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='text8']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#text8</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fb547f3f-84b2-45f8-bce2-4259f493b262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>50398a70-8cae-4ade-9752-e5188edd6367</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text8</value>
      <webElementGuid>19cd7051-6817-4d46-9436-025e03d2d09d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text8&quot;)</value>
      <webElementGuid>f908415b-20b7-45f1-8e16-283e31d89353</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text8']</value>
      <webElementGuid>1e84cba8-773e-49d5-b2e0-c976aa5c7022</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[8]</value>
      <webElementGuid>adf96642-25f8-48e6-8d4b-9a7f314b0751</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text8']</value>
      <webElementGuid>689183f4-c5dc-4cdf-a574-2b10558bdcd9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
