<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Radio9_radio10</name>
   <tag></tag>
   <elementGuidId>5c5ef6f1-daa5-4bb7-8ef2-d63de2bec273</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radio10']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#radio10</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>550f2f22-a766-4e3a-a82e-5945b3217e76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>6570b837-d26a-4833-87bd-066cfb02e7b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio10</value>
      <webElementGuid>4b0b9664-f93f-4b94-869d-380004115d70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Radio10</value>
      <webElementGuid>506192d5-4f2a-4c8a-a7db-c42e3eda00f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio10&quot;)</value>
      <webElementGuid>36564649-ced3-4f34-af0e-d267dd8e6469</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radio10']</value>
      <webElementGuid>fb7240e2-7363-4575-9abe-9ee6c7b2fb77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[30]</value>
      <webElementGuid>59f8e51a-96f2-42d1-9cb5-0f46d15cc7f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'radio10']</value>
      <webElementGuid>6525072e-40c7-4d33-980e-2934ba351a13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
